spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_db
    username: root
    password: root
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 100000

app:
  check-client-api-header: true
  client-api-key: 12345
