version: '3'
services:
  postgres:
    image: postgres:14-alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES-DB=app_db
    volumes:
      - ./init.sql:/docker-entrypoint-db/init.sql
